// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomOS.Core.Data;

#nullable disable

namespace RoomOS.Core.Data.Migrations
{
    [DbContext(typeof(RoomOsDbContext))]
    [Migration("20260919140416_Routines")]
    partial class Routines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RoomOS.Core.Data.Entities.AudioOutput", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("friendly_name");

                    b.Property<string>("MatchHint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("match_hint");

                    b.Property<string>("PcDeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pc_device_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("WindowsDeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("windows_device_id");

                    b.HasKey("Id");

                    b.HasIndex("PcDeviceId");

                    b.ToTable("audio_outputs", (string)null);
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.IntegrationToken", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token");

                    b.HasKey("Provider");

                    b.ToTable("integration_tokens", (string)null);
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Routine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("days");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<int>("MinuteOfDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minute_of_day");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SceneId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scene_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("routines", (string)null);
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Scene", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("room_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("steps_json");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.AudioOutput", b =>
                {
                    b.HasOne("RoomOS.Core.Data.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("PcDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Device", b =>
                {
                    b.HasOne("RoomOS.Core.Data.Entities.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Routine", b =>
                {
                    b.HasOne("RoomOS.Core.Data.Entities.Scene", null)
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Scene", b =>
                {
                    b.HasOne("RoomOS.Core.Data.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomOS.Core.Data.Entities.Room", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
